### ISSUE TITLE
[BUG] Codegen closes after newpage in browser

### ISSUE THREAD

**Issue by gkaizer** [microsoft/playwright-cli#168] opened 2020-12-15 09:24 UTC
OS: Windows 10 x64, node.js v15.0.1 npm v7.0.3
I'm trying to record javascript code in a console window as Administrator:
npx playwright-cli codegen -o miabiblio-dl.js https://www.lamiabiblioteca.com
Browser chromium opens, load page without problems, but whenever I try to open a new tab or even if I paste a new url in the address bar of first tab, browser closes (I tryed also with -b ff to use firefox instead, but it is the same)
I uninstalled playwright-cli, restarted windows and after the above command asked to install playwright-cli, which I did, but nothing changed. Am I missing anything?

**Comment by pavelfeldman** [comment] 2020-12-17 05:51
You should update to the latest version! Having said that, only one tab recording is supported.

**Comment by dgozman** [comment] 2021-01-27 20:53
We are unable to reproduce this issue. I'd suggest a fresh start, with a new playwright version (1.8.0 is the latest right now). Note that `playwright-cli` has been merged with playwright, so use `npx playwright` instead.
```sh
# Check the version
$ npx playwright --version

# Run
$ npx playwright codegen
```
Please reopen if the issue persists.

**Closed by dgozman** 2021-01-27 20:53 UTC
