### ISSUE TITLE
Chromium element selection broken

### ISSUE THREAD

**Issue by LVMuser** [microsoft/playwright-cli#183] opened 2020-12-21 17:43 UTC
as per the example in your docs:

`npx playwright-cli open wikipedia.org`

and in the developer console:

`playwright.$('text=English')`

produced the following error, on reproduced on Windows and Mac

```
Uncaught TypeError: parsed.parts is not iterable
    at ConsoleAPI._checkSelector (eval at extend ((index):2071), <anonymous>:322:39)
    at ConsoleAPI.querySelector (eval at extend ((index):2071), <anonymous>:331:14)
    at Object.$ (eval at extend ((index):2071), <anonymous>:315:35)
    at <anonymous>:1:12
_checkSelector @ VM17:322
querySelector @ VM17:331
$ @ VM17:315
(anonymous) @ VM98:1
```

**Comment by LVMuser** [comment] 2020-12-22 10:56
Didn't mention version, broken on `1.7.0`. Dropped back to `1.6.2` and issue not present

**Comment by jsntrmn** [comment] 2020-12-31 21:09
I can confirm the same issue exists on Firefox and WebKit, too.

From CLI:

```zsh
$ npx playwright-cli --version
Version 0.171.0
$ npx playwright-cli ff wikipedia.org
$ npx playwright-cli wk wikipedia.org
```

In developer console of Firefox:

```javascript
playwright.$('text=English')
Uncaught TypeError: this._injectedScript.engines is undefined
    _checkSelector debugger eval code line 1987 > eval:323
    querySelector debugger eval code line 1987 > eval:331
    $ debugger eval code line 1987 > eval:315
    <anonymous> debugger eval code:1
    getEvalResult resource://devtools/server/actors/webconsole/eval-with-debugger.js:243
    evalWithDebugger resource://devtools/server/actors/webconsole/eval-with-debugger.js:167
    evaluateJS resource://devtools/server/actors/webconsole.js:1113
    evaluateJSAsync resource://devtools/server/actors/webconsole.js:1007
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
```

In developer console of WebKit:

```javascript
playwright.$('text=English')
TypeError: undefined is not an object (evaluating 'this._injectedScript.engines.has')
_checkSelector
querySelector
Global Code
evaluateWithScopeExtension
(anonymous function)
_wrapCall
```

**Comment by rubentorresbonet** [comment] 2021-01-08 10:10
I also have this issue. Any workaround?

**Comment by FokkeZB** [comment] 2021-01-18 13:19
I get yet another:

```
playwright.$('.auth-form >> text=Log in');
VM53:323 Uncaught TypeError: Cannot read property 'has' of undefined
    at ConsoleAPI._checkSelector (eval at extend (login:1), <anonymous>:323:47)
    at ConsoleAPI.querySelector (eval at extend (login:1), <anonymous>:331:14)
    at Object.$ (eval at extend (login:1), <anonymous>:315:35)
    at <anonymous>:1:12
```

**Comment by dgozman** [comment] 2021-01-27 21:18
This works for me with `npx playwright` version 1.8.0. This seems like a regression in `playwright-cli@0.170.0`, please upgrade to get it fixed. Note that `playwright-cli` has been merged into playwright, so use `npx playwright` instead. Sorry for the inconvenience.

**Closed by dgozman** 2021-01-27 21:18 UTC
