### ISSUE TITLE
No output support for codegen command

### ISSUE THREAD

**Issue by dareksob** [microsoft/playwright-cli#79] opened 2020-09-24 13:05 UTC
I saw in the master source that the command codegen should support a output option. 
If I try that inside the command line I only get a error message.

Master source code
``````
program
    .command('codegen [url]')
    .description('open page and generate code for user actions')
    .option('-o --output <file name>', 'saves the generated script to a file')
    .action(function(url, command) {
      codegen(command.parent, url, command.output);
    }).on('--help', function() {
      console.log('');
      console.log('Examples:');
      console.log('');
      console.log('  $ record');
      console.log('  $ -b webkit record https://example.com');
    });
``````

``````
playwright-cli codegen -o login.js localhost:8090
error: unknown option '-o'
``````

playwright-cli -V
Version 0.5.2

**Comment by arjun27** [comment] 2020-09-24 20:01
Thanks for reporting, @dareksob. Closing as duplicate of #77 (see [comment](https://github.com/microsoft/playwright-cli/issues/77#issuecomment-698546260)).

**Closed by arjun27** 2020-09-24 20:01 UTC

**Comment by mxschmitt** [comment] 2020-09-24 21:39
@dareksob We have now a version available with the latest features: `npm install plawright-cli@next`
