### ISSUE TITLE
Codegen behaves inconsistently across browsers

### ISSUE THREAD

**Issue by rmallof** [microsoft/playwright-cli#182] opened 2020-12-20 23:44 UTC
Hi,

first of all, thank you for maintaining this awesome repo :)

I've been playing around with it and I'm facing issues with **FireFox** when visiting google.com:

`playwright-cli -b ff codegen google.com`

The following pop-up appears and I'm not able to click any button to accept it and/or close it:

![image](https://user-images.githubusercontent.com/3352772/102727296-247db080-4325-11eb-9138-90c0da9dfd7f.png)

I've found issues with select html tags while using **Chrome**:

`playwright-cli codegen https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select`

I was not able to choose any car in the dropdown list

For further details, please, see the related issue: https://github.com/microsoft/playwright-cli/issues/80#issuecomment-746926860

Thanks!

**Comment by dgozman** [comment] 2021-01-27 21:16
Unfortunately, I am not able to reproduce this issue, because this dialog does not pop up.

I am also able to record selects on Chromium using the latest `npx playwright` (note that `playwright-cli` has been merged to playwright).

Please reopen if the issue persists and you have repro steps.

**Closed by dgozman** 2021-01-27 21:16 UTC
